---

services:
  demo-nginx:
    build: ./docker
    container_name: demo-nginx-${ENVIRONMENT:-dev}
    ports:
      - "${NGINX_PORT:-8080}:80"
    env_file:
      - .env.${ENVIRONMENT:-dev}
    environment:
      # Override with workflow-specific vars
      - DEPLOY_TIME=${DEPLOY_TIME}
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - APP_VERSION=${APP_VERSION:-dev}
    restart: unless-stopped
    labels:
      - "demo.environment=${ENVIRONMENT}"
      - "demo.version=${APP_VERSION}"
      - "demo.deployed-by=github-actions"

networks:
  default:
    name: demo-network-${ENVIRONMENT:-dev}
