name: Test Runner Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Test runner
      run: |
        echo "Runner is working!"
        hostname
        whoami
        docker --version
